version: '3.9'
services:
  api:
    build:
      context: ../backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../backend:/code
    working_dir: /code
    ports:
      - '8000:8000'
    environment:
      - PYTHONPATH=/code
  web:
    build:
      context: ../frontend
    command: npm start
    volumes:
      - ../frontend:/app
    working_dir: /app
    ports:
      - '4200:4200'
    environment:
      - CHOKIDAR_USEPOLLING=true
